#############################################################################
# Makefile for building: cs195u_engine
# Generated by qmake (3.1) (Qt 5.11.3)
# Project:  cs195u_engine.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile cs195u_engine.pro -spec linux-g++ CONFIG+=debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++14 -g -g -std=gnu++1y -W -Waddress -Warray-bounds -Wc++0x-compat -Wchar-subscripts -Wformat -Wmain -Wmissing-braces -Wparentheses -Wreorder -Wreturn-type -Wsequence-point -Wsign-compare -Wstrict-overflow=1 -Wswitch -Wtrigraphs -Wuninitialized -Wunused-label -Wunused-variable -Wvolatile-register-var -Wno-extra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Isrc -Ilibs -Iglm -Ilibs/glew-1.10.0/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = cs195u_engine1.0.0
DISTDIR = /gpfs/main/home/apeter10/course/cs1950u/engine/warmup/.tmp/cs195u_engine1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -lGLU -lQt5OpenGL -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = libs/glew-1.10.0/src/glew.c \
		src/main.cpp \
		src/mainwindow.cpp \
		src/view.cpp \
		src/viewformat.cpp \
		src/engine/graphics/ResourceLoader.cpp \
		src/engine/graphics/FBO.cpp \
		src/engine/graphics/IBO.cpp \
		src/engine/graphics/Texture.cpp \
		src/engine/graphics/Texture1D.cpp \
		src/engine/graphics/Texture2D.cpp \
		src/engine/graphics/Texture3D.cpp \
		src/engine/graphics/VAO.cpp \
		src/engine/graphics/VBO.cpp \
		src/engine/graphics/VBOAttribMarker.cpp \
		src/engine/graphics/Font.cpp \
		src/engine/graphics/DepthBuffer.cpp \
		src/engine/graphics/RenderBuffer.cpp \
		src/engine/graphics/GraphicsDebug.cpp \
		src/engine/graphics/Shader.cpp \
		src/engine/graphics/Camera.cpp \
		src/engine/graphics/Shape.cpp \
		src/engine/graphics/Graphics.cpp \
		src/engine/graphics/Material.cpp \
		src/engine/graphics/Light.cpp qrc_shaders.cpp \
		qrc_fonts.cpp \
		qrc_images.cpp \
		moc_mainwindow.cpp \
		moc_view.cpp
OBJECTS       = glew.o \
		main.o \
		mainwindow.o \
		view.o \
		viewformat.o \
		ResourceLoader.o \
		FBO.o \
		IBO.o \
		Texture.o \
		Texture1D.o \
		Texture2D.o \
		Texture3D.o \
		VAO.o \
		VBO.o \
		VBOAttribMarker.o \
		Font.o \
		DepthBuffer.o \
		RenderBuffer.o \
		GraphicsDebug.o \
		Shader.o \
		Camera.o \
		Shape.o \
		Graphics.o \
		Material.o \
		Light.o \
		qrc_shaders.o \
		qrc_fonts.o \
		qrc_images.o \
		moc_mainwindow.o \
		moc_view.o
DIST          = res/shaders/shader.vert \
		res/shaders/shader.frag \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		cs195u_engine.pro libs/glew-1.10.0/include/GL/glew.h \
		libs/stb/stb_rect_pack.h \
		libs/stb/stb_truetype.h \
		src/mainwindow.h \
		src/view.h \
		src/viewformat.h \
		src/engine/util/CommonIncludes.h \
		src/engine/graphics/ResourceLoader.h \
		src/engine/graphics/CylinderData.h \
		src/engine/graphics/SphereData.h \
		src/engine/graphics/FBO.h \
		src/engine/graphics/IBO.h \
		src/engine/graphics/Texture.h \
		src/engine/graphics/Texture1D.h \
		src/engine/graphics/Texture2D.h \
		src/engine/graphics/Texture3D.h \
		src/engine/graphics/VAO.h \
		src/engine/graphics/VBO.h \
		src/engine/graphics/VBOAttribMarker.h \
		src/engine/graphics/CubeData.h \
		src/engine/graphics/Font.h \
		src/engine/graphics/DepthBuffer.h \
		src/engine/graphics/RenderBuffer.h \
		src/engine/graphics/GraphicsDebug.h \
		src/engine/graphics/Shader.h \
		src/engine/graphics/ShaderAttribLocations.h \
		src/engine/graphics/Camera.h \
		src/engine/graphics/Graphics.h \
		src/engine/graphics/Shape.h \
		src/engine/graphics/Material.h \
		src/engine/graphics/Light.h \
		src/engine/graphics/Constants.h libs/glew-1.10.0/src/glew.c \
		src/main.cpp \
		src/mainwindow.cpp \
		src/view.cpp \
		src/viewformat.cpp \
		src/engine/graphics/ResourceLoader.cpp \
		src/engine/graphics/FBO.cpp \
		src/engine/graphics/IBO.cpp \
		src/engine/graphics/Texture.cpp \
		src/engine/graphics/Texture1D.cpp \
		src/engine/graphics/Texture2D.cpp \
		src/engine/graphics/Texture3D.cpp \
		src/engine/graphics/VAO.cpp \
		src/engine/graphics/VBO.cpp \
		src/engine/graphics/VBOAttribMarker.cpp \
		src/engine/graphics/Font.cpp \
		src/engine/graphics/DepthBuffer.cpp \
		src/engine/graphics/RenderBuffer.cpp \
		src/engine/graphics/GraphicsDebug.cpp \
		src/engine/graphics/Shader.cpp \
		src/engine/graphics/Camera.cpp \
		src/engine/graphics/Shape.cpp \
		src/engine/graphics/Graphics.cpp \
		src/engine/graphics/Material.cpp \
		src/engine/graphics/Light.cpp
QMAKE_TARGET  = cs195u_engine
DESTDIR       = 
TARGET        = cs195u_engine


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cs195u_engine.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		cs195u_engine.pro \
		res/shaders/shaders.qrc \
		res/fonts/fonts.qrc \
		res/images/images.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5OpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile cs195u_engine.pro -spec linux-g++ CONFIG+=debug
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
cs195u_engine.pro:
res/shaders/shaders.qrc:
res/fonts/fonts.qrc:
res/images/images.qrc:
/usr/lib/x86_64-linux-gnu/libQt5OpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile cs195u_engine.pro -spec linux-g++ CONFIG+=debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents res/shaders/shaders.qrc res/fonts/fonts.qrc res/images/images.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents libs/glew-1.10.0/include/GL/glew.h libs/stb/stb_rect_pack.h libs/stb/stb_truetype.h src/mainwindow.h src/view.h src/viewformat.h src/engine/util/CommonIncludes.h src/engine/graphics/ResourceLoader.h src/engine/graphics/CylinderData.h src/engine/graphics/SphereData.h src/engine/graphics/FBO.h src/engine/graphics/IBO.h src/engine/graphics/Texture.h src/engine/graphics/Texture1D.h src/engine/graphics/Texture2D.h src/engine/graphics/Texture3D.h src/engine/graphics/VAO.h src/engine/graphics/VBO.h src/engine/graphics/VBOAttribMarker.h src/engine/graphics/CubeData.h src/engine/graphics/Font.h src/engine/graphics/DepthBuffer.h src/engine/graphics/RenderBuffer.h src/engine/graphics/GraphicsDebug.h src/engine/graphics/Shader.h src/engine/graphics/ShaderAttribLocations.h src/engine/graphics/Camera.h src/engine/graphics/Graphics.h src/engine/graphics/Shape.h src/engine/graphics/Material.h src/engine/graphics/Light.h src/engine/graphics/Constants.h $(DISTDIR)/
	$(COPY_FILE) --parents libs/glew-1.10.0/src/glew.c src/main.cpp src/mainwindow.cpp src/view.cpp src/viewformat.cpp src/engine/graphics/ResourceLoader.cpp src/engine/graphics/FBO.cpp src/engine/graphics/IBO.cpp src/engine/graphics/Texture.cpp src/engine/graphics/Texture1D.cpp src/engine/graphics/Texture2D.cpp src/engine/graphics/Texture3D.cpp src/engine/graphics/VAO.cpp src/engine/graphics/VBO.cpp src/engine/graphics/VBOAttribMarker.cpp src/engine/graphics/Font.cpp src/engine/graphics/DepthBuffer.cpp src/engine/graphics/RenderBuffer.cpp src/engine/graphics/GraphicsDebug.cpp src/engine/graphics/Shader.cpp src/engine/graphics/Camera.cpp src/engine/graphics/Shape.cpp src/engine/graphics/Graphics.cpp src/engine/graphics/Material.cpp src/engine/graphics/Light.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_shaders.cpp qrc_fonts.cpp qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_shaders.cpp qrc_fonts.cpp qrc_images.cpp
qrc_shaders.cpp: res/shaders/shaders.qrc \
		/usr/lib/qt5/bin/rcc \
		res/shaders/shader.frag \
		res/shaders/shader.vert
	/usr/lib/qt5/bin/rcc -name shaders res/shaders/shaders.qrc -o qrc_shaders.cpp

qrc_fonts.cpp: res/fonts/fonts.qrc \
		/usr/lib/qt5/bin/rcc \
		res/fonts/OpenSans-Regular.ttf
	/usr/lib/qt5/bin/rcc -name fonts res/fonts/fonts.qrc -o qrc_fonts.cpp

qrc_images.cpp: res/images/images.qrc \
		/usr/lib/qt5/bin/rcc \
		res/images/grass.png
	/usr/lib/qt5/bin/rcc -name images res/images/images.qrc -o qrc_images.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=c++14 -g -g -std=gnu++1y -W -Waddress -Warray-bounds -Wc++0x-compat -Wchar-subscripts -Wformat -Wmain -Wmissing-braces -Wparentheses -Wreorder -Wreturn-type -Wsequence-point -Wsign-compare -Wstrict-overflow=1 -Wswitch -Wtrigraphs -Wuninitialized -Wunused-label -Wunused-variable -Wvolatile-register-var -Wno-extra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_view.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_view.cpp
moc_mainwindow.cpp: src/mainwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /gpfs/main/home/apeter10/course/cs1950u/engine/warmup/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/gpfs/main/home/apeter10/course/cs1950u/engine/warmup -I/gpfs/main/home/apeter10/course/cs1950u/engine/warmup/src -I/gpfs/main/home/apeter10/course/cs1950u/engine/warmup/libs -I/gpfs/main/home/apeter10/course/cs1950u/engine/warmup/glm -I/gpfs/main/home/apeter10/course/cs1950u/engine/warmup/libs/glew-1.10.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/mainwindow.h -o moc_mainwindow.cpp

moc_view.cpp: src/engine/util/CommonIncludes.h \
		libs/glew-1.10.0/include/GL/glew.h \
		libs/glm/glm.hpp \
		libs/glm/detail/_fixes.hpp \
		libs/glm/fwd.hpp \
		libs/glm/detail/type_int.hpp \
		libs/glm/detail/setup.hpp \
		libs/glm/detail/type_float.hpp \
		libs/glm/detail/type_vec.hpp \
		libs/glm/detail/precision.hpp \
		libs/glm/detail/type_mat.hpp \
		libs/glm/vec2.hpp \
		libs/glm/detail/type_vec2.hpp \
		libs/glm/detail/_swizzle.hpp \
		libs/glm/detail/_swizzle_func.hpp \
		libs/glm/detail/type_vec2.inl \
		libs/glm/vec3.hpp \
		libs/glm/detail/type_vec3.hpp \
		libs/glm/detail/type_vec3.inl \
		libs/glm/vec4.hpp \
		libs/glm/detail/type_vec4.hpp \
		libs/glm/detail/type_vec4.inl \
		libs/glm/mat2x2.hpp \
		libs/glm/detail/type_mat2x2.hpp \
		libs/glm/detail/type_mat2x2.inl \
		libs/glm/mat2x3.hpp \
		libs/glm/detail/type_mat2x3.hpp \
		libs/glm/detail/type_mat2x3.inl \
		libs/glm/mat2x4.hpp \
		libs/glm/detail/type_mat2x4.hpp \
		libs/glm/detail/type_mat2x4.inl \
		libs/glm/mat3x2.hpp \
		libs/glm/detail/type_mat3x2.hpp \
		libs/glm/detail/type_mat3x2.inl \
		libs/glm/mat3x3.hpp \
		libs/glm/detail/type_mat3x3.hpp \
		libs/glm/detail/type_mat3x3.inl \
		libs/glm/mat3x4.hpp \
		libs/glm/detail/type_mat3x4.hpp \
		libs/glm/detail/type_mat3x4.inl \
		libs/glm/mat4x2.hpp \
		libs/glm/detail/type_mat4x2.hpp \
		libs/glm/detail/type_mat4x2.inl \
		libs/glm/mat4x3.hpp \
		libs/glm/detail/type_mat4x3.hpp \
		libs/glm/detail/type_mat4x3.inl \
		libs/glm/mat4x4.hpp \
		libs/glm/detail/type_mat4x4.hpp \
		libs/glm/detail/type_mat4x4.inl \
		libs/glm/trigonometric.hpp \
		libs/glm/detail/func_trigonometric.hpp \
		libs/glm/detail/func_trigonometric.inl \
		libs/glm/detail/_vectorize.hpp \
		libs/glm/detail/type_vec1.hpp \
		libs/glm/detail/type_vec1.inl \
		libs/glm/exponential.hpp \
		libs/glm/detail/func_exponential.hpp \
		libs/glm/detail/func_exponential.inl \
		libs/glm/detail/func_vector_relational.hpp \
		libs/glm/detail/func_vector_relational.inl \
		libs/glm/common.hpp \
		libs/glm/detail/func_common.hpp \
		libs/glm/detail/func_common.inl \
		libs/glm/packing.hpp \
		libs/glm/detail/func_packing.hpp \
		libs/glm/detail/func_packing.inl \
		libs/glm/detail/type_half.hpp \
		libs/glm/detail/type_half.inl \
		libs/glm/geometric.hpp \
		libs/glm/detail/func_geometric.hpp \
		libs/glm/detail/func_geometric.inl \
		libs/glm/matrix.hpp \
		libs/glm/detail/func_matrix.hpp \
		libs/glm/detail/func_matrix.inl \
		libs/glm/vector_relational.hpp \
		libs/glm/integer.hpp \
		libs/glm/detail/func_integer.hpp \
		libs/glm/detail/func_integer.inl \
		libs/glm/gtx/string_cast.hpp \
		libs/glm/gtx/integer.hpp \
		libs/glm/gtx/integer.inl \
		libs/glm/gtx/quaternion.hpp \
		libs/glm/gtc/constants.hpp \
		libs/glm/gtc/constants.inl \
		libs/glm/gtc/quaternion.hpp \
		libs/glm/gtx/quaternion.inl \
		libs/glm/gtx/norm.hpp \
		libs/glm/gtx/norm.inl \
		libs/glm/gtx/string_cast.inl \
		libs/glm/gtx/transform.hpp \
		libs/glm/gtc/matrix_transform.hpp \
		libs/glm/gtc/matrix_transform.inl \
		libs/glm/gtx/transform.inl \
		libs/glm/gtc/type_ptr.hpp \
		libs/glm/gtc/type_ptr.inl \
		src/view.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /gpfs/main/home/apeter10/course/cs1950u/engine/warmup/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/gpfs/main/home/apeter10/course/cs1950u/engine/warmup -I/gpfs/main/home/apeter10/course/cs1950u/engine/warmup/src -I/gpfs/main/home/apeter10/course/cs1950u/engine/warmup/libs -I/gpfs/main/home/apeter10/course/cs1950u/engine/warmup/glm -I/gpfs/main/home/apeter10/course/cs1950u/engine/warmup/libs/glew-1.10.0/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/view.h -o moc_view.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: src/mainwindow.ui \
		/usr/lib/qt5/bin/uic \
		src/view.h \
		src/engine/util/CommonIncludes.h \
		libs/glew-1.10.0/include/GL/glew.h \
		libs/glm/glm.hpp \
		libs/glm/detail/_fixes.hpp \
		libs/glm/fwd.hpp \
		libs/glm/detail/type_int.hpp \
		libs/glm/detail/setup.hpp \
		libs/glm/detail/type_float.hpp \
		libs/glm/detail/type_vec.hpp \
		libs/glm/detail/precision.hpp \
		libs/glm/detail/type_mat.hpp \
		libs/glm/vec2.hpp \
		libs/glm/detail/type_vec2.hpp \
		libs/glm/detail/_swizzle.hpp \
		libs/glm/detail/_swizzle_func.hpp \
		libs/glm/detail/type_vec2.inl \
		libs/glm/vec3.hpp \
		libs/glm/detail/type_vec3.hpp \
		libs/glm/detail/type_vec3.inl \
		libs/glm/vec4.hpp \
		libs/glm/detail/type_vec4.hpp \
		libs/glm/detail/type_vec4.inl \
		libs/glm/mat2x2.hpp \
		libs/glm/detail/type_mat2x2.hpp \
		libs/glm/detail/type_mat2x2.inl \
		libs/glm/mat2x3.hpp \
		libs/glm/detail/type_mat2x3.hpp \
		libs/glm/detail/type_mat2x3.inl \
		libs/glm/mat2x4.hpp \
		libs/glm/detail/type_mat2x4.hpp \
		libs/glm/detail/type_mat2x4.inl \
		libs/glm/mat3x2.hpp \
		libs/glm/detail/type_mat3x2.hpp \
		libs/glm/detail/type_mat3x2.inl \
		libs/glm/mat3x3.hpp \
		libs/glm/detail/type_mat3x3.hpp \
		libs/glm/detail/type_mat3x3.inl \
		libs/glm/mat3x4.hpp \
		libs/glm/detail/type_mat3x4.hpp \
		libs/glm/detail/type_mat3x4.inl \
		libs/glm/mat4x2.hpp \
		libs/glm/detail/type_mat4x2.hpp \
		libs/glm/detail/type_mat4x2.inl \
		libs/glm/mat4x3.hpp \
		libs/glm/detail/type_mat4x3.hpp \
		libs/glm/detail/type_mat4x3.inl \
		libs/glm/mat4x4.hpp \
		libs/glm/detail/type_mat4x4.hpp \
		libs/glm/detail/type_mat4x4.inl \
		libs/glm/trigonometric.hpp \
		libs/glm/detail/func_trigonometric.hpp \
		libs/glm/detail/func_trigonometric.inl \
		libs/glm/detail/_vectorize.hpp \
		libs/glm/detail/type_vec1.hpp \
		libs/glm/detail/type_vec1.inl \
		libs/glm/exponential.hpp \
		libs/glm/detail/func_exponential.hpp \
		libs/glm/detail/func_exponential.inl \
		libs/glm/detail/func_vector_relational.hpp \
		libs/glm/detail/func_vector_relational.inl \
		libs/glm/common.hpp \
		libs/glm/detail/func_common.hpp \
		libs/glm/detail/func_common.inl \
		libs/glm/packing.hpp \
		libs/glm/detail/func_packing.hpp \
		libs/glm/detail/func_packing.inl \
		libs/glm/detail/type_half.hpp \
		libs/glm/detail/type_half.inl \
		libs/glm/geometric.hpp \
		libs/glm/detail/func_geometric.hpp \
		libs/glm/detail/func_geometric.inl \
		libs/glm/matrix.hpp \
		libs/glm/detail/func_matrix.hpp \
		libs/glm/detail/func_matrix.inl \
		libs/glm/vector_relational.hpp \
		libs/glm/integer.hpp \
		libs/glm/detail/func_integer.hpp \
		libs/glm/detail/func_integer.inl \
		libs/glm/gtx/string_cast.hpp \
		libs/glm/gtx/integer.hpp \
		libs/glm/gtx/integer.inl \
		libs/glm/gtx/quaternion.hpp \
		libs/glm/gtc/constants.hpp \
		libs/glm/gtc/constants.inl \
		libs/glm/gtc/quaternion.hpp \
		libs/glm/gtx/quaternion.inl \
		libs/glm/gtx/norm.hpp \
		libs/glm/gtx/norm.inl \
		libs/glm/gtx/string_cast.inl \
		libs/glm/gtx/transform.hpp \
		libs/glm/gtc/matrix_transform.hpp \
		libs/glm/gtc/matrix_transform.inl \
		libs/glm/gtx/transform.inl \
		libs/glm/gtc/type_ptr.hpp \
		libs/glm/gtc/type_ptr.inl
	/usr/lib/qt5/bin/uic src/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

glew.o: libs/glew-1.10.0/src/glew.c libs/glew-1.10.0/include/GL/glew.h \
		libs/glew-1.10.0/include/GL/wglew.h \
		libs/glew-1.10.0/include/GL/glxew.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o glew.o libs/glew-1.10.0/src/glew.c

main.o: src/main.cpp src/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		ui_mainwindow.h \
		src/view.h \
		src/engine/util/CommonIncludes.h \
		libs/glew-1.10.0/include/GL/glew.h \
		libs/glm/glm.hpp \
		libs/glm/detail/_fixes.hpp \
		libs/glm/fwd.hpp \
		libs/glm/detail/type_int.hpp \
		libs/glm/detail/setup.hpp \
		libs/glm/detail/type_float.hpp \
		libs/glm/detail/type_vec.hpp \
		libs/glm/detail/precision.hpp \
		libs/glm/detail/type_mat.hpp \
		libs/glm/vec2.hpp \
		libs/glm/detail/type_vec2.hpp \
		libs/glm/detail/_swizzle.hpp \
		libs/glm/detail/_swizzle_func.hpp \
		libs/glm/detail/type_vec2.inl \
		libs/glm/vec3.hpp \
		libs/glm/detail/type_vec3.hpp \
		libs/glm/detail/type_vec3.inl \
		libs/glm/vec4.hpp \
		libs/glm/detail/type_vec4.hpp \
		libs/glm/detail/type_vec4.inl \
		libs/glm/mat2x2.hpp \
		libs/glm/detail/type_mat2x2.hpp \
		libs/glm/detail/type_mat2x2.inl \
		libs/glm/mat2x3.hpp \
		libs/glm/detail/type_mat2x3.hpp \
		libs/glm/detail/type_mat2x3.inl \
		libs/glm/mat2x4.hpp \
		libs/glm/detail/type_mat2x4.hpp \
		libs/glm/detail/type_mat2x4.inl \
		libs/glm/mat3x2.hpp \
		libs/glm/detail/type_mat3x2.hpp \
		libs/glm/detail/type_mat3x2.inl \
		libs/glm/mat3x3.hpp \
		libs/glm/detail/type_mat3x3.hpp \
		libs/glm/detail/type_mat3x3.inl \
		libs/glm/mat3x4.hpp \
		libs/glm/detail/type_mat3x4.hpp \
		libs/glm/detail/type_mat3x4.inl \
		libs/glm/mat4x2.hpp \
		libs/glm/detail/type_mat4x2.hpp \
		libs/glm/detail/type_mat4x2.inl \
		libs/glm/mat4x3.hpp \
		libs/glm/detail/type_mat4x3.hpp \
		libs/glm/detail/type_mat4x3.inl \
		libs/glm/mat4x4.hpp \
		libs/glm/detail/type_mat4x4.hpp \
		libs/glm/detail/type_mat4x4.inl \
		libs/glm/trigonometric.hpp \
		libs/glm/detail/func_trigonometric.hpp \
		libs/glm/detail/func_trigonometric.inl \
		libs/glm/detail/_vectorize.hpp \
		libs/glm/detail/type_vec1.hpp \
		libs/glm/detail/type_vec1.inl \
		libs/glm/exponential.hpp \
		libs/glm/detail/func_exponential.hpp \
		libs/glm/detail/func_exponential.inl \
		libs/glm/detail/func_vector_relational.hpp \
		libs/glm/detail/func_vector_relational.inl \
		libs/glm/common.hpp \
		libs/glm/detail/func_common.hpp \
		libs/glm/detail/func_common.inl \
		libs/glm/packing.hpp \
		libs/glm/detail/func_packing.hpp \
		libs/glm/detail/func_packing.inl \
		libs/glm/detail/type_half.hpp \
		libs/glm/detail/type_half.inl \
		libs/glm/geometric.hpp \
		libs/glm/detail/func_geometric.hpp \
		libs/glm/detail/func_geometric.inl \
		libs/glm/matrix.hpp \
		libs/glm/detail/func_matrix.hpp \
		libs/glm/detail/func_matrix.inl \
		libs/glm/vector_relational.hpp \
		libs/glm/integer.hpp \
		libs/glm/detail/func_integer.hpp \
		libs/glm/detail/func_integer.inl \
		libs/glm/gtx/string_cast.hpp \
		libs/glm/gtx/integer.hpp \
		libs/glm/gtx/integer.inl \
		libs/glm/gtx/quaternion.hpp \
		libs/glm/gtc/constants.hpp \
		libs/glm/gtc/constants.inl \
		libs/glm/gtc/quaternion.hpp \
		libs/glm/gtx/quaternion.inl \
		libs/glm/gtx/norm.hpp \
		libs/glm/gtx/norm.inl \
		libs/glm/gtx/string_cast.inl \
		libs/glm/gtx/transform.hpp \
		libs/glm/gtc/matrix_transform.hpp \
		libs/glm/gtc/matrix_transform.inl \
		libs/glm/gtx/transform.inl \
		libs/glm/gtc/type_ptr.hpp \
		libs/glm/gtc/type_ptr.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

view.o: src/view.cpp src/view.h \
		src/engine/util/CommonIncludes.h \
		libs/glew-1.10.0/include/GL/glew.h \
		libs/glm/glm.hpp \
		libs/glm/detail/_fixes.hpp \
		libs/glm/fwd.hpp \
		libs/glm/detail/type_int.hpp \
		libs/glm/detail/setup.hpp \
		libs/glm/detail/type_float.hpp \
		libs/glm/detail/type_vec.hpp \
		libs/glm/detail/precision.hpp \
		libs/glm/detail/type_mat.hpp \
		libs/glm/vec2.hpp \
		libs/glm/detail/type_vec2.hpp \
		libs/glm/detail/_swizzle.hpp \
		libs/glm/detail/_swizzle_func.hpp \
		libs/glm/detail/type_vec2.inl \
		libs/glm/vec3.hpp \
		libs/glm/detail/type_vec3.hpp \
		libs/glm/detail/type_vec3.inl \
		libs/glm/vec4.hpp \
		libs/glm/detail/type_vec4.hpp \
		libs/glm/detail/type_vec4.inl \
		libs/glm/mat2x2.hpp \
		libs/glm/detail/type_mat2x2.hpp \
		libs/glm/detail/type_mat2x2.inl \
		libs/glm/mat2x3.hpp \
		libs/glm/detail/type_mat2x3.hpp \
		libs/glm/detail/type_mat2x3.inl \
		libs/glm/mat2x4.hpp \
		libs/glm/detail/type_mat2x4.hpp \
		libs/glm/detail/type_mat2x4.inl \
		libs/glm/mat3x2.hpp \
		libs/glm/detail/type_mat3x2.hpp \
		libs/glm/detail/type_mat3x2.inl \
		libs/glm/mat3x3.hpp \
		libs/glm/detail/type_mat3x3.hpp \
		libs/glm/detail/type_mat3x3.inl \
		libs/glm/mat3x4.hpp \
		libs/glm/detail/type_mat3x4.hpp \
		libs/glm/detail/type_mat3x4.inl \
		libs/glm/mat4x2.hpp \
		libs/glm/detail/type_mat4x2.hpp \
		libs/glm/detail/type_mat4x2.inl \
		libs/glm/mat4x3.hpp \
		libs/glm/detail/type_mat4x3.hpp \
		libs/glm/detail/type_mat4x3.inl \
		libs/glm/mat4x4.hpp \
		libs/glm/detail/type_mat4x4.hpp \
		libs/glm/detail/type_mat4x4.inl \
		libs/glm/trigonometric.hpp \
		libs/glm/detail/func_trigonometric.hpp \
		libs/glm/detail/func_trigonometric.inl \
		libs/glm/detail/_vectorize.hpp \
		libs/glm/detail/type_vec1.hpp \
		libs/glm/detail/type_vec1.inl \
		libs/glm/exponential.hpp \
		libs/glm/detail/func_exponential.hpp \
		libs/glm/detail/func_exponential.inl \
		libs/glm/detail/func_vector_relational.hpp \
		libs/glm/detail/func_vector_relational.inl \
		libs/glm/common.hpp \
		libs/glm/detail/func_common.hpp \
		libs/glm/detail/func_common.inl \
		libs/glm/packing.hpp \
		libs/glm/detail/func_packing.hpp \
		libs/glm/detail/func_packing.inl \
		libs/glm/detail/type_half.hpp \
		libs/glm/detail/type_half.inl \
		libs/glm/geometric.hpp \
		libs/glm/detail/func_geometric.hpp \
		libs/glm/detail/func_geometric.inl \
		libs/glm/matrix.hpp \
		libs/glm/detail/func_matrix.hpp \
		libs/glm/detail/func_matrix.inl \
		libs/glm/vector_relational.hpp \
		libs/glm/integer.hpp \
		libs/glm/detail/func_integer.hpp \
		libs/glm/detail/func_integer.inl \
		libs/glm/gtx/string_cast.hpp \
		libs/glm/gtx/integer.hpp \
		libs/glm/gtx/integer.inl \
		libs/glm/gtx/quaternion.hpp \
		libs/glm/gtc/constants.hpp \
		libs/glm/gtc/constants.inl \
		libs/glm/gtc/quaternion.hpp \
		libs/glm/gtx/quaternion.inl \
		libs/glm/gtx/norm.hpp \
		libs/glm/gtx/norm.inl \
		libs/glm/gtx/string_cast.inl \
		libs/glm/gtx/transform.hpp \
		libs/glm/gtc/matrix_transform.hpp \
		libs/glm/gtc/matrix_transform.inl \
		libs/glm/gtx/transform.inl \
		libs/glm/gtc/type_ptr.hpp \
		libs/glm/gtc/type_ptr.inl \
		src/viewformat.h \
		src/engine/graphics/GraphicsDebug.h \
		src/engine/graphics/Graphics.h \
		src/engine/graphics/Shader.h \
		src/engine/graphics/VBO.h \
		src/engine/graphics/Constants.h \
		src/engine/graphics/Material.h \
		src/engine/graphics/Light.h \
		src/engine/graphics/Camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o view.o src/view.cpp

viewformat.o: src/viewformat.cpp src/viewformat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewformat.o src/viewformat.cpp

ResourceLoader.o: src/engine/graphics/ResourceLoader.cpp src/engine/graphics/ResourceLoader.h \
		libs/glew-1.10.0/include/GL/glew.h \
		src/engine/util/CommonIncludes.h \
		libs/glm/glm.hpp \
		libs/glm/detail/_fixes.hpp \
		libs/glm/fwd.hpp \
		libs/glm/detail/type_int.hpp \
		libs/glm/detail/setup.hpp \
		libs/glm/detail/type_float.hpp \
		libs/glm/detail/type_vec.hpp \
		libs/glm/detail/precision.hpp \
		libs/glm/detail/type_mat.hpp \
		libs/glm/vec2.hpp \
		libs/glm/detail/type_vec2.hpp \
		libs/glm/detail/_swizzle.hpp \
		libs/glm/detail/_swizzle_func.hpp \
		libs/glm/detail/type_vec2.inl \
		libs/glm/vec3.hpp \
		libs/glm/detail/type_vec3.hpp \
		libs/glm/detail/type_vec3.inl \
		libs/glm/vec4.hpp \
		libs/glm/detail/type_vec4.hpp \
		libs/glm/detail/type_vec4.inl \
		libs/glm/mat2x2.hpp \
		libs/glm/detail/type_mat2x2.hpp \
		libs/glm/detail/type_mat2x2.inl \
		libs/glm/mat2x3.hpp \
		libs/glm/detail/type_mat2x3.hpp \
		libs/glm/detail/type_mat2x3.inl \
		libs/glm/mat2x4.hpp \
		libs/glm/detail/type_mat2x4.hpp \
		libs/glm/detail/type_mat2x4.inl \
		libs/glm/mat3x2.hpp \
		libs/glm/detail/type_mat3x2.hpp \
		libs/glm/detail/type_mat3x2.inl \
		libs/glm/mat3x3.hpp \
		libs/glm/detail/type_mat3x3.hpp \
		libs/glm/detail/type_mat3x3.inl \
		libs/glm/mat3x4.hpp \
		libs/glm/detail/type_mat3x4.hpp \
		libs/glm/detail/type_mat3x4.inl \
		libs/glm/mat4x2.hpp \
		libs/glm/detail/type_mat4x2.hpp \
		libs/glm/detail/type_mat4x2.inl \
		libs/glm/mat4x3.hpp \
		libs/glm/detail/type_mat4x3.hpp \
		libs/glm/detail/type_mat4x3.inl \
		libs/glm/mat4x4.hpp \
		libs/glm/detail/type_mat4x4.hpp \
		libs/glm/detail/type_mat4x4.inl \
		libs/glm/trigonometric.hpp \
		libs/glm/detail/func_trigonometric.hpp \
		libs/glm/detail/func_trigonometric.inl \
		libs/glm/detail/_vectorize.hpp \
		libs/glm/detail/type_vec1.hpp \
		libs/glm/detail/type_vec1.inl \
		libs/glm/exponential.hpp \
		libs/glm/detail/func_exponential.hpp \
		libs/glm/detail/func_exponential.inl \
		libs/glm/detail/func_vector_relational.hpp \
		libs/glm/detail/func_vector_relational.inl \
		libs/glm/common.hpp \
		libs/glm/detail/func_common.hpp \
		libs/glm/detail/func_common.inl \
		libs/glm/packing.hpp \
		libs/glm/detail/func_packing.hpp \
		libs/glm/detail/func_packing.inl \
		libs/glm/detail/type_half.hpp \
		libs/glm/detail/type_half.inl \
		libs/glm/geometric.hpp \
		libs/glm/detail/func_geometric.hpp \
		libs/glm/detail/func_geometric.inl \
		libs/glm/matrix.hpp \
		libs/glm/detail/func_matrix.hpp \
		libs/glm/detail/func_matrix.inl \
		libs/glm/vector_relational.hpp \
		libs/glm/integer.hpp \
		libs/glm/detail/func_integer.hpp \
		libs/glm/detail/func_integer.inl \
		libs/glm/gtx/string_cast.hpp \
		libs/glm/gtx/integer.hpp \
		libs/glm/gtx/integer.inl \
		libs/glm/gtx/quaternion.hpp \
		libs/glm/gtc/constants.hpp \
		libs/glm/gtc/constants.inl \
		libs/glm/gtc/quaternion.hpp \
		libs/glm/gtx/quaternion.inl \
		libs/glm/gtx/norm.hpp \
		libs/glm/gtx/norm.inl \
		libs/glm/gtx/string_cast.inl \
		libs/glm/gtx/transform.hpp \
		libs/glm/gtc/matrix_transform.hpp \
		libs/glm/gtc/matrix_transform.inl \
		libs/glm/gtx/transform.inl \
		libs/glm/gtc/type_ptr.hpp \
		libs/glm/gtc/type_ptr.inl \
		src/engine/graphics/Shape.h \
		src/engine/graphics/VBO.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ResourceLoader.o src/engine/graphics/ResourceLoader.cpp

FBO.o: src/engine/graphics/FBO.cpp src/engine/graphics/FBO.h \
		src/engine/graphics/Texture.h \
		src/engine/util/CommonIncludes.h \
		libs/glew-1.10.0/include/GL/glew.h \
		libs/glm/glm.hpp \
		libs/glm/detail/_fixes.hpp \
		libs/glm/fwd.hpp \
		libs/glm/detail/type_int.hpp \
		libs/glm/detail/setup.hpp \
		libs/glm/detail/type_float.hpp \
		libs/glm/detail/type_vec.hpp \
		libs/glm/detail/precision.hpp \
		libs/glm/detail/type_mat.hpp \
		libs/glm/vec2.hpp \
		libs/glm/detail/type_vec2.hpp \
		libs/glm/detail/_swizzle.hpp \
		libs/glm/detail/_swizzle_func.hpp \
		libs/glm/detail/type_vec2.inl \
		libs/glm/vec3.hpp \
		libs/glm/detail/type_vec3.hpp \
		libs/glm/detail/type_vec3.inl \
		libs/glm/vec4.hpp \
		libs/glm/detail/type_vec4.hpp \
		libs/glm/detail/type_vec4.inl \
		libs/glm/mat2x2.hpp \
		libs/glm/detail/type_mat2x2.hpp \
		libs/glm/detail/type_mat2x2.inl \
		libs/glm/mat2x3.hpp \
		libs/glm/detail/type_mat2x3.hpp \
		libs/glm/detail/type_mat2x3.inl \
		libs/glm/mat2x4.hpp \
		libs/glm/detail/type_mat2x4.hpp \
		libs/glm/detail/type_mat2x4.inl \
		libs/glm/mat3x2.hpp \
		libs/glm/detail/type_mat3x2.hpp \
		libs/glm/detail/type_mat3x2.inl \
		libs/glm/mat3x3.hpp \
		libs/glm/detail/type_mat3x3.hpp \
		libs/glm/detail/type_mat3x3.inl \
		libs/glm/mat3x4.hpp \
		libs/glm/detail/type_mat3x4.hpp \
		libs/glm/detail/type_mat3x4.inl \
		libs/glm/mat4x2.hpp \
		libs/glm/detail/type_mat4x2.hpp \
		libs/glm/detail/type_mat4x2.inl \
		libs/glm/mat4x3.hpp \
		libs/glm/detail/type_mat4x3.hpp \
		libs/glm/detail/type_mat4x3.inl \
		libs/glm/mat4x4.hpp \
		libs/glm/detail/type_mat4x4.hpp \
		libs/glm/detail/type_mat4x4.inl \
		libs/glm/trigonometric.hpp \
		libs/glm/detail/func_trigonometric.hpp \
		libs/glm/detail/func_trigonometric.inl \
		libs/glm/detail/_vectorize.hpp \
		libs/glm/detail/type_vec1.hpp \
		libs/glm/detail/type_vec1.inl \
		libs/glm/exponential.hpp \
		libs/glm/detail/func_exponential.hpp \
		libs/glm/detail/func_exponential.inl \
		libs/glm/detail/func_vector_relational.hpp \
		libs/glm/detail/func_vector_relational.inl \
		libs/glm/common.hpp \
		libs/glm/detail/func_common.hpp \
		libs/glm/detail/func_common.inl \
		libs/glm/packing.hpp \
		libs/glm/detail/func_packing.hpp \
		libs/glm/detail/func_packing.inl \
		libs/glm/detail/type_half.hpp \
		libs/glm/detail/type_half.inl \
		libs/glm/geometric.hpp \
		libs/glm/detail/func_geometric.hpp \
		libs/glm/detail/func_geometric.inl \
		libs/glm/matrix.hpp \
		libs/glm/detail/func_matrix.hpp \
		libs/glm/detail/func_matrix.inl \
		libs/glm/vector_relational.hpp \
		libs/glm/integer.hpp \
		libs/glm/detail/func_integer.hpp \
		libs/glm/detail/func_integer.inl \
		libs/glm/gtx/string_cast.hpp \
		libs/glm/gtx/integer.hpp \
		libs/glm/gtx/integer.inl \
		libs/glm/gtx/quaternion.hpp \
		libs/glm/gtc/constants.hpp \
		libs/glm/gtc/constants.inl \
		libs/glm/gtc/quaternion.hpp \
		libs/glm/gtx/quaternion.inl \
		libs/glm/gtx/norm.hpp \
		libs/glm/gtx/norm.inl \
		libs/glm/gtx/string_cast.inl \
		libs/glm/gtx/transform.hpp \
		libs/glm/gtc/matrix_transform.hpp \
		libs/glm/gtc/matrix_transform.inl \
		libs/glm/gtx/transform.inl \
		libs/glm/gtc/type_ptr.hpp \
		libs/glm/gtc/type_ptr.inl \
		src/engine/graphics/GraphicsDebug.h \
		src/engine/graphics/RenderBuffer.h \
		src/engine/graphics/DepthBuffer.h \
		src/engine/graphics/Texture2D.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FBO.o src/engine/graphics/FBO.cpp

IBO.o: src/engine/graphics/IBO.cpp src/engine/graphics/IBO.h \
		libs/glew-1.10.0/include/GL/glew.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IBO.o src/engine/graphics/IBO.cpp

Texture.o: src/engine/graphics/Texture.cpp src/engine/graphics/Texture.h \
		src/engine/util/CommonIncludes.h \
		libs/glew-1.10.0/include/GL/glew.h \
		libs/glm/glm.hpp \
		libs/glm/detail/_fixes.hpp \
		libs/glm/fwd.hpp \
		libs/glm/detail/type_int.hpp \
		libs/glm/detail/setup.hpp \
		libs/glm/detail/type_float.hpp \
		libs/glm/detail/type_vec.hpp \
		libs/glm/detail/precision.hpp \
		libs/glm/detail/type_mat.hpp \
		libs/glm/vec2.hpp \
		libs/glm/detail/type_vec2.hpp \
		libs/glm/detail/_swizzle.hpp \
		libs/glm/detail/_swizzle_func.hpp \
		libs/glm/detail/type_vec2.inl \
		libs/glm/vec3.hpp \
		libs/glm/detail/type_vec3.hpp \
		libs/glm/detail/type_vec3.inl \
		libs/glm/vec4.hpp \
		libs/glm/detail/type_vec4.hpp \
		libs/glm/detail/type_vec4.inl \
		libs/glm/mat2x2.hpp \
		libs/glm/detail/type_mat2x2.hpp \
		libs/glm/detail/type_mat2x2.inl \
		libs/glm/mat2x3.hpp \
		libs/glm/detail/type_mat2x3.hpp \
		libs/glm/detail/type_mat2x3.inl \
		libs/glm/mat2x4.hpp \
		libs/glm/detail/type_mat2x4.hpp \
		libs/glm/detail/type_mat2x4.inl \
		libs/glm/mat3x2.hpp \
		libs/glm/detail/type_mat3x2.hpp \
		libs/glm/detail/type_mat3x2.inl \
		libs/glm/mat3x3.hpp \
		libs/glm/detail/type_mat3x3.hpp \
		libs/glm/detail/type_mat3x3.inl \
		libs/glm/mat3x4.hpp \
		libs/glm/detail/type_mat3x4.hpp \
		libs/glm/detail/type_mat3x4.inl \
		libs/glm/mat4x2.hpp \
		libs/glm/detail/type_mat4x2.hpp \
		libs/glm/detail/type_mat4x2.inl \
		libs/glm/mat4x3.hpp \
		libs/glm/detail/type_mat4x3.hpp \
		libs/glm/detail/type_mat4x3.inl \
		libs/glm/mat4x4.hpp \
		libs/glm/detail/type_mat4x4.hpp \
		libs/glm/detail/type_mat4x4.inl \
		libs/glm/trigonometric.hpp \
		libs/glm/detail/func_trigonometric.hpp \
		libs/glm/detail/func_trigonometric.inl \
		libs/glm/detail/_vectorize.hpp \
		libs/glm/detail/type_vec1.hpp \
		libs/glm/detail/type_vec1.inl \
		libs/glm/exponential.hpp \
		libs/glm/detail/func_exponential.hpp \
		libs/glm/detail/func_exponential.inl \
		libs/glm/detail/func_vector_relational.hpp \
		libs/glm/detail/func_vector_relational.inl \
		libs/glm/common.hpp \
		libs/glm/detail/func_common.hpp \
		libs/glm/detail/func_common.inl \
		libs/glm/packing.hpp \
		libs/glm/detail/func_packing.hpp \
		libs/glm/detail/func_packing.inl \
		libs/glm/detail/type_half.hpp \
		libs/glm/detail/type_half.inl \
		libs/glm/geometric.hpp \
		libs/glm/detail/func_geometric.hpp \
		libs/glm/detail/func_geometric.inl \
		libs/glm/matrix.hpp \
		libs/glm/detail/func_matrix.hpp \
		libs/glm/detail/func_matrix.inl \
		libs/glm/vector_relational.hpp \
		libs/glm/integer.hpp \
		libs/glm/detail/func_integer.hpp \
		libs/glm/detail/func_integer.inl \
		libs/glm/gtx/string_cast.hpp \
		libs/glm/gtx/integer.hpp \
		libs/glm/gtx/integer.inl \
		libs/glm/gtx/quaternion.hpp \
		libs/glm/gtc/constants.hpp \
		libs/glm/gtc/constants.inl \
		libs/glm/gtc/quaternion.hpp \
		libs/glm/gtx/quaternion.inl \
		libs/glm/gtx/norm.hpp \
		libs/glm/gtx/norm.inl \
		libs/glm/gtx/string_cast.inl \
		libs/glm/gtx/transform.hpp \
		libs/glm/gtc/matrix_transform.hpp \
		libs/glm/gtc/matrix_transform.inl \
		libs/glm/gtx/transform.inl \
		libs/glm/gtc/type_ptr.hpp \
		libs/glm/gtc/type_ptr.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Texture.o src/engine/graphics/Texture.cpp

Texture1D.o: src/engine/graphics/Texture1D.cpp src/engine/graphics/Texture1D.h \
		src/engine/graphics/Texture.h \
		src/engine/util/CommonIncludes.h \
		libs/glew-1.10.0/include/GL/glew.h \
		libs/glm/glm.hpp \
		libs/glm/detail/_fixes.hpp \
		libs/glm/fwd.hpp \
		libs/glm/detail/type_int.hpp \
		libs/glm/detail/setup.hpp \
		libs/glm/detail/type_float.hpp \
		libs/glm/detail/type_vec.hpp \
		libs/glm/detail/precision.hpp \
		libs/glm/detail/type_mat.hpp \
		libs/glm/vec2.hpp \
		libs/glm/detail/type_vec2.hpp \
		libs/glm/detail/_swizzle.hpp \
		libs/glm/detail/_swizzle_func.hpp \
		libs/glm/detail/type_vec2.inl \
		libs/glm/vec3.hpp \
		libs/glm/detail/type_vec3.hpp \
		libs/glm/detail/type_vec3.inl \
		libs/glm/vec4.hpp \
		libs/glm/detail/type_vec4.hpp \
		libs/glm/detail/type_vec4.inl \
		libs/glm/mat2x2.hpp \
		libs/glm/detail/type_mat2x2.hpp \
		libs/glm/detail/type_mat2x2.inl \
		libs/glm/mat2x3.hpp \
		libs/glm/detail/type_mat2x3.hpp \
		libs/glm/detail/type_mat2x3.inl \
		libs/glm/mat2x4.hpp \
		libs/glm/detail/type_mat2x4.hpp \
		libs/glm/detail/type_mat2x4.inl \
		libs/glm/mat3x2.hpp \
		libs/glm/detail/type_mat3x2.hpp \
		libs/glm/detail/type_mat3x2.inl \
		libs/glm/mat3x3.hpp \
		libs/glm/detail/type_mat3x3.hpp \
		libs/glm/detail/type_mat3x3.inl \
		libs/glm/mat3x4.hpp \
		libs/glm/detail/type_mat3x4.hpp \
		libs/glm/detail/type_mat3x4.inl \
		libs/glm/mat4x2.hpp \
		libs/glm/detail/type_mat4x2.hpp \
		libs/glm/detail/type_mat4x2.inl \
		libs/glm/mat4x3.hpp \
		libs/glm/detail/type_mat4x3.hpp \
		libs/glm/detail/type_mat4x3.inl \
		libs/glm/mat4x4.hpp \
		libs/glm/detail/type_mat4x4.hpp \
		libs/glm/detail/type_mat4x4.inl \
		libs/glm/trigonometric.hpp \
		libs/glm/detail/func_trigonometric.hpp \
		libs/glm/detail/func_trigonometric.inl \
		libs/glm/detail/_vectorize.hpp \
		libs/glm/detail/type_vec1.hpp \
		libs/glm/detail/type_vec1.inl \
		libs/glm/exponential.hpp \
		libs/glm/detail/func_exponential.hpp \
		libs/glm/detail/func_exponential.inl \
		libs/glm/detail/func_vector_relational.hpp \
		libs/glm/detail/func_vector_relational.inl \
		libs/glm/common.hpp \
		libs/glm/detail/func_common.hpp \
		libs/glm/detail/func_common.inl \
		libs/glm/packing.hpp \
		libs/glm/detail/func_packing.hpp \
		libs/glm/detail/func_packing.inl \
		libs/glm/detail/type_half.hpp \
		libs/glm/detail/type_half.inl \
		libs/glm/geometric.hpp \
		libs/glm/detail/func_geometric.hpp \
		libs/glm/detail/func_geometric.inl \
		libs/glm/matrix.hpp \
		libs/glm/detail/func_matrix.hpp \
		libs/glm/detail/func_matrix.inl \
		libs/glm/vector_relational.hpp \
		libs/glm/integer.hpp \
		libs/glm/detail/func_integer.hpp \
		libs/glm/detail/func_integer.inl \
		libs/glm/gtx/string_cast.hpp \
		libs/glm/gtx/integer.hpp \
		libs/glm/gtx/integer.inl \
		libs/glm/gtx/quaternion.hpp \
		libs/glm/gtc/constants.hpp \
		libs/glm/gtc/constants.inl \
		libs/glm/gtc/quaternion.hpp \
		libs/glm/gtx/quaternion.inl \
		libs/glm/gtx/norm.hpp \
		libs/glm/gtx/norm.inl \
		libs/glm/gtx/string_cast.inl \
		libs/glm/gtx/transform.hpp \
		libs/glm/gtc/matrix_transform.hpp \
		libs/glm/gtc/matrix_transform.inl \
		libs/glm/gtx/transform.inl \
		libs/glm/gtc/type_ptr.hpp \
		libs/glm/gtc/type_ptr.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Texture1D.o src/engine/graphics/Texture1D.cpp

Texture2D.o: src/engine/graphics/Texture2D.cpp src/engine/graphics/Texture2D.h \
		src/engine/graphics/Texture.h \
		src/engine/util/CommonIncludes.h \
		libs/glew-1.10.0/include/GL/glew.h \
		libs/glm/glm.hpp \
		libs/glm/detail/_fixes.hpp \
		libs/glm/fwd.hpp \
		libs/glm/detail/type_int.hpp \
		libs/glm/detail/setup.hpp \
		libs/glm/detail/type_float.hpp \
		libs/glm/detail/type_vec.hpp \
		libs/glm/detail/precision.hpp \
		libs/glm/detail/type_mat.hpp \
		libs/glm/vec2.hpp \
		libs/glm/detail/type_vec2.hpp \
		libs/glm/detail/_swizzle.hpp \
		libs/glm/detail/_swizzle_func.hpp \
		libs/glm/detail/type_vec2.inl \
		libs/glm/vec3.hpp \
		libs/glm/detail/type_vec3.hpp \
		libs/glm/detail/type_vec3.inl \
		libs/glm/vec4.hpp \
		libs/glm/detail/type_vec4.hpp \
		libs/glm/detail/type_vec4.inl \
		libs/glm/mat2x2.hpp \
		libs/glm/detail/type_mat2x2.hpp \
		libs/glm/detail/type_mat2x2.inl \
		libs/glm/mat2x3.hpp \
		libs/glm/detail/type_mat2x3.hpp \
		libs/glm/detail/type_mat2x3.inl \
		libs/glm/mat2x4.hpp \
		libs/glm/detail/type_mat2x4.hpp \
		libs/glm/detail/type_mat2x4.inl \
		libs/glm/mat3x2.hpp \
		libs/glm/detail/type_mat3x2.hpp \
		libs/glm/detail/type_mat3x2.inl \
		libs/glm/mat3x3.hpp \
		libs/glm/detail/type_mat3x3.hpp \
		libs/glm/detail/type_mat3x3.inl \
		libs/glm/mat3x4.hpp \
		libs/glm/detail/type_mat3x4.hpp \
		libs/glm/detail/type_mat3x4.inl \
		libs/glm/mat4x2.hpp \
		libs/glm/detail/type_mat4x2.hpp \
		libs/glm/detail/type_mat4x2.inl \
		libs/glm/mat4x3.hpp \
		libs/glm/detail/type_mat4x3.hpp \
		libs/glm/detail/type_mat4x3.inl \
		libs/glm/mat4x4.hpp \
		libs/glm/detail/type_mat4x4.hpp \
		libs/glm/detail/type_mat4x4.inl \
		libs/glm/trigonometric.hpp \
		libs/glm/detail/func_trigonometric.hpp \
		libs/glm/detail/func_trigonometric.inl \
		libs/glm/detail/_vectorize.hpp \
		libs/glm/detail/type_vec1.hpp \
		libs/glm/detail/type_vec1.inl \
		libs/glm/exponential.hpp \
		libs/glm/detail/func_exponential.hpp \
		libs/glm/detail/func_exponential.inl \
		libs/glm/detail/func_vector_relational.hpp \
		libs/glm/detail/func_vector_relational.inl \
		libs/glm/common.hpp \
		libs/glm/detail/func_common.hpp \
		libs/glm/detail/func_common.inl \
		libs/glm/packing.hpp \
		libs/glm/detail/func_packing.hpp \
		libs/glm/detail/func_packing.inl \
		libs/glm/detail/type_half.hpp \
		libs/glm/detail/type_half.inl \
		libs/glm/geometric.hpp \
		libs/glm/detail/func_geometric.hpp \
		libs/glm/detail/func_geometric.inl \
		libs/glm/matrix.hpp \
		libs/glm/detail/func_matrix.hpp \
		libs/glm/detail/func_matrix.inl \
		libs/glm/vector_relational.hpp \
		libs/glm/integer.hpp \
		libs/glm/detail/func_integer.hpp \
		libs/glm/detail/func_integer.inl \
		libs/glm/gtx/string_cast.hpp \
		libs/glm/gtx/integer.hpp \
		libs/glm/gtx/integer.inl \
		libs/glm/gtx/quaternion.hpp \
		libs/glm/gtc/constants.hpp \
		libs/glm/gtc/constants.inl \
		libs/glm/gtc/quaternion.hpp \
		libs/glm/gtx/quaternion.inl \
		libs/glm/gtx/norm.hpp \
		libs/glm/gtx/norm.inl \
		libs/glm/gtx/string_cast.inl \
		libs/glm/gtx/transform.hpp \
		libs/glm/gtc/matrix_transform.hpp \
		libs/glm/gtc/matrix_transform.inl \
		libs/glm/gtx/transform.inl \
		libs/glm/gtc/type_ptr.hpp \
		libs/glm/gtc/type_ptr.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Texture2D.o src/engine/graphics/Texture2D.cpp

Texture3D.o: src/engine/graphics/Texture3D.cpp src/engine/graphics/Texture3D.h \
		src/engine/graphics/Texture.h \
		src/engine/util/CommonIncludes.h \
		libs/glew-1.10.0/include/GL/glew.h \
		libs/glm/glm.hpp \
		libs/glm/detail/_fixes.hpp \
		libs/glm/fwd.hpp \
		libs/glm/detail/type_int.hpp \
		libs/glm/detail/setup.hpp \
		libs/glm/detail/type_float.hpp \
		libs/glm/detail/type_vec.hpp \
		libs/glm/detail/precision.hpp \
		libs/glm/detail/type_mat.hpp \
		libs/glm/vec2.hpp \
		libs/glm/detail/type_vec2.hpp \
		libs/glm/detail/_swizzle.hpp \
		libs/glm/detail/_swizzle_func.hpp \
		libs/glm/detail/type_vec2.inl \
		libs/glm/vec3.hpp \
		libs/glm/detail/type_vec3.hpp \
		libs/glm/detail/type_vec3.inl \
		libs/glm/vec4.hpp \
		libs/glm/detail/type_vec4.hpp \
		libs/glm/detail/type_vec4.inl \
		libs/glm/mat2x2.hpp \
		libs/glm/detail/type_mat2x2.hpp \
		libs/glm/detail/type_mat2x2.inl \
		libs/glm/mat2x3.hpp \
		libs/glm/detail/type_mat2x3.hpp \
		libs/glm/detail/type_mat2x3.inl \
		libs/glm/mat2x4.hpp \
		libs/glm/detail/type_mat2x4.hpp \
		libs/glm/detail/type_mat2x4.inl \
		libs/glm/mat3x2.hpp \
		libs/glm/detail/type_mat3x2.hpp \
		libs/glm/detail/type_mat3x2.inl \
		libs/glm/mat3x3.hpp \
		libs/glm/detail/type_mat3x3.hpp \
		libs/glm/detail/type_mat3x3.inl \
		libs/glm/mat3x4.hpp \
		libs/glm/detail/type_mat3x4.hpp \
		libs/glm/detail/type_mat3x4.inl \
		libs/glm/mat4x2.hpp \
		libs/glm/detail/type_mat4x2.hpp \
		libs/glm/detail/type_mat4x2.inl \
		libs/glm/mat4x3.hpp \
		libs/glm/detail/type_mat4x3.hpp \
		libs/glm/detail/type_mat4x3.inl \
		libs/glm/mat4x4.hpp \
		libs/glm/detail/type_mat4x4.hpp \
		libs/glm/detail/type_mat4x4.inl \
		libs/glm/trigonometric.hpp \
		libs/glm/detail/func_trigonometric.hpp \
		libs/glm/detail/func_trigonometric.inl \
		libs/glm/detail/_vectorize.hpp \
		libs/glm/detail/type_vec1.hpp \
		libs/glm/detail/type_vec1.inl \
		libs/glm/exponential.hpp \
		libs/glm/detail/func_exponential.hpp \
		libs/glm/detail/func_exponential.inl \
		libs/glm/detail/func_vector_relational.hpp \
		libs/glm/detail/func_vector_relational.inl \
		libs/glm/common.hpp \
		libs/glm/detail/func_common.hpp \
		libs/glm/detail/func_common.inl \
		libs/glm/packing.hpp \
		libs/glm/detail/func_packing.hpp \
		libs/glm/detail/func_packing.inl \
		libs/glm/detail/type_half.hpp \
		libs/glm/detail/type_half.inl \
		libs/glm/geometric.hpp \
		libs/glm/detail/func_geometric.hpp \
		libs/glm/detail/func_geometric.inl \
		libs/glm/matrix.hpp \
		libs/glm/detail/func_matrix.hpp \
		libs/glm/detail/func_matrix.inl \
		libs/glm/vector_relational.hpp \
		libs/glm/integer.hpp \
		libs/glm/detail/func_integer.hpp \
		libs/glm/detail/func_integer.inl \
		libs/glm/gtx/string_cast.hpp \
		libs/glm/gtx/integer.hpp \
		libs/glm/gtx/integer.inl \
		libs/glm/gtx/quaternion.hpp \
		libs/glm/gtc/constants.hpp \
		libs/glm/gtc/constants.inl \
		libs/glm/gtc/quaternion.hpp \
		libs/glm/gtx/quaternion.inl \
		libs/glm/gtx/norm.hpp \
		libs/glm/gtx/norm.inl \
		libs/glm/gtx/string_cast.inl \
		libs/glm/gtx/transform.hpp \
		libs/glm/gtc/matrix_transform.hpp \
		libs/glm/gtc/matrix_transform.inl \
		libs/glm/gtx/transform.inl \
		libs/glm/gtc/type_ptr.hpp \
		libs/glm/gtc/type_ptr.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Texture3D.o src/engine/graphics/Texture3D.cpp

VAO.o: src/engine/graphics/VAO.cpp src/engine/graphics/VAO.h \
		libs/glew-1.10.0/include/GL/glew.h \
		src/engine/graphics/VBO.h \
		src/engine/graphics/IBO.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VAO.o src/engine/graphics/VAO.cpp

VBO.o: src/engine/graphics/VBO.cpp src/engine/graphics/VBO.h \
		libs/glew-1.10.0/include/GL/glew.h \
		src/engine/graphics/VBOAttribMarker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VBO.o src/engine/graphics/VBO.cpp

VBOAttribMarker.o: src/engine/graphics/VBOAttribMarker.cpp src/engine/graphics/VBOAttribMarker.h \
		libs/glew-1.10.0/include/GL/glew.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VBOAttribMarker.o src/engine/graphics/VBOAttribMarker.cpp

Font.o: src/engine/graphics/Font.cpp src/engine/graphics/Font.h \
		src/engine/util/CommonIncludes.h \
		libs/glew-1.10.0/include/GL/glew.h \
		libs/glm/glm.hpp \
		libs/glm/detail/_fixes.hpp \
		libs/glm/fwd.hpp \
		libs/glm/detail/type_int.hpp \
		libs/glm/detail/setup.hpp \
		libs/glm/detail/type_float.hpp \
		libs/glm/detail/type_vec.hpp \
		libs/glm/detail/precision.hpp \
		libs/glm/detail/type_mat.hpp \
		libs/glm/vec2.hpp \
		libs/glm/detail/type_vec2.hpp \
		libs/glm/detail/_swizzle.hpp \
		libs/glm/detail/_swizzle_func.hpp \
		libs/glm/detail/type_vec2.inl \
		libs/glm/vec3.hpp \
		libs/glm/detail/type_vec3.hpp \
		libs/glm/detail/type_vec3.inl \
		libs/glm/vec4.hpp \
		libs/glm/detail/type_vec4.hpp \
		libs/glm/detail/type_vec4.inl \
		libs/glm/mat2x2.hpp \
		libs/glm/detail/type_mat2x2.hpp \
		libs/glm/detail/type_mat2x2.inl \
		libs/glm/mat2x3.hpp \
		libs/glm/detail/type_mat2x3.hpp \
		libs/glm/detail/type_mat2x3.inl \
		libs/glm/mat2x4.hpp \
		libs/glm/detail/type_mat2x4.hpp \
		libs/glm/detail/type_mat2x4.inl \
		libs/glm/mat3x2.hpp \
		libs/glm/detail/type_mat3x2.hpp \
		libs/glm/detail/type_mat3x2.inl \
		libs/glm/mat3x3.hpp \
		libs/glm/detail/type_mat3x3.hpp \
		libs/glm/detail/type_mat3x3.inl \
		libs/glm/mat3x4.hpp \
		libs/glm/detail/type_mat3x4.hpp \
		libs/glm/detail/type_mat3x4.inl \
		libs/glm/mat4x2.hpp \
		libs/glm/detail/type_mat4x2.hpp \
		libs/glm/detail/type_mat4x2.inl \
		libs/glm/mat4x3.hpp \
		libs/glm/detail/type_mat4x3.hpp \
		libs/glm/detail/type_mat4x3.inl \
		libs/glm/mat4x4.hpp \
		libs/glm/detail/type_mat4x4.hpp \
		libs/glm/detail/type_mat4x4.inl \
		libs/glm/trigonometric.hpp \
		libs/glm/detail/func_trigonometric.hpp \
		libs/glm/detail/func_trigonometric.inl \
		libs/glm/detail/_vectorize.hpp \
		libs/glm/detail/type_vec1.hpp \
		libs/glm/detail/type_vec1.inl \
		libs/glm/exponential.hpp \
		libs/glm/detail/func_exponential.hpp \
		libs/glm/detail/func_exponential.inl \
		libs/glm/detail/func_vector_relational.hpp \
		libs/glm/detail/func_vector_relational.inl \
		libs/glm/common.hpp \
		libs/glm/detail/func_common.hpp \
		libs/glm/detail/func_common.inl \
		libs/glm/packing.hpp \
		libs/glm/detail/func_packing.hpp \
		libs/glm/detail/func_packing.inl \
		libs/glm/detail/type_half.hpp \
		libs/glm/detail/type_half.inl \
		libs/glm/geometric.hpp \
		libs/glm/detail/func_geometric.hpp \
		libs/glm/detail/func_geometric.inl \
		libs/glm/matrix.hpp \
		libs/glm/detail/func_matrix.hpp \
		libs/glm/detail/func_matrix.inl \
		libs/glm/vector_relational.hpp \
		libs/glm/integer.hpp \
		libs/glm/detail/func_integer.hpp \
		libs/glm/detail/func_integer.inl \
		libs/glm/gtx/string_cast.hpp \
		libs/glm/gtx/integer.hpp \
		libs/glm/gtx/integer.inl \
		libs/glm/gtx/quaternion.hpp \
		libs/glm/gtc/constants.hpp \
		libs/glm/gtc/constants.inl \
		libs/glm/gtc/quaternion.hpp \
		libs/glm/gtx/quaternion.inl \
		libs/glm/gtx/norm.hpp \
		libs/glm/gtx/norm.inl \
		libs/glm/gtx/string_cast.inl \
		libs/glm/gtx/transform.hpp \
		libs/glm/gtc/matrix_transform.hpp \
		libs/glm/gtc/matrix_transform.inl \
		libs/glm/gtx/transform.inl \
		libs/glm/gtc/type_ptr.hpp \
		libs/glm/gtc/type_ptr.inl \
		libs/stb/stb_rect_pack.h \
		libs/stb/stb_truetype.h \
		src/engine/graphics/Graphics.h \
		src/engine/graphics/Shader.h \
		src/engine/graphics/VBO.h \
		src/engine/graphics/GraphicsDebug.h \
		src/engine/graphics/Constants.h \
		src/engine/graphics/Material.h \
		src/engine/graphics/Light.h \
		src/engine/graphics/Texture2D.h \
		src/engine/graphics/Texture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Font.o src/engine/graphics/Font.cpp

DepthBuffer.o: src/engine/graphics/DepthBuffer.cpp src/engine/graphics/DepthBuffer.h \
		src/engine/graphics/RenderBuffer.h \
		libs/glew-1.10.0/include/GL/glew.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DepthBuffer.o src/engine/graphics/DepthBuffer.cpp

RenderBuffer.o: src/engine/graphics/RenderBuffer.cpp src/engine/graphics/RenderBuffer.h \
		libs/glew-1.10.0/include/GL/glew.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RenderBuffer.o src/engine/graphics/RenderBuffer.cpp

GraphicsDebug.o: src/engine/graphics/GraphicsDebug.cpp src/engine/graphics/GraphicsDebug.h \
		libs/glew-1.10.0/include/GL/glew.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GraphicsDebug.o src/engine/graphics/GraphicsDebug.cpp

Shader.o: src/engine/graphics/Shader.cpp src/engine/graphics/Shader.h \
		libs/glew-1.10.0/include/GL/glew.h \
		libs/glm/glm.hpp \
		libs/glm/detail/_fixes.hpp \
		libs/glm/fwd.hpp \
		libs/glm/detail/type_int.hpp \
		libs/glm/detail/setup.hpp \
		libs/glm/detail/type_float.hpp \
		libs/glm/detail/type_vec.hpp \
		libs/glm/detail/precision.hpp \
		libs/glm/detail/type_mat.hpp \
		libs/glm/vec2.hpp \
		libs/glm/detail/type_vec2.hpp \
		libs/glm/detail/_swizzle.hpp \
		libs/glm/detail/_swizzle_func.hpp \
		libs/glm/detail/type_vec2.inl \
		libs/glm/vec3.hpp \
		libs/glm/detail/type_vec3.hpp \
		libs/glm/detail/type_vec3.inl \
		libs/glm/vec4.hpp \
		libs/glm/detail/type_vec4.hpp \
		libs/glm/detail/type_vec4.inl \
		libs/glm/mat2x2.hpp \
		libs/glm/detail/type_mat2x2.hpp \
		libs/glm/detail/type_mat2x2.inl \
		libs/glm/mat2x3.hpp \
		libs/glm/detail/type_mat2x3.hpp \
		libs/glm/detail/type_mat2x3.inl \
		libs/glm/mat2x4.hpp \
		libs/glm/detail/type_mat2x4.hpp \
		libs/glm/detail/type_mat2x4.inl \
		libs/glm/mat3x2.hpp \
		libs/glm/detail/type_mat3x2.hpp \
		libs/glm/detail/type_mat3x2.inl \
		libs/glm/mat3x3.hpp \
		libs/glm/detail/type_mat3x3.hpp \
		libs/glm/detail/type_mat3x3.inl \
		libs/glm/mat3x4.hpp \
		libs/glm/detail/type_mat3x4.hpp \
		libs/glm/detail/type_mat3x4.inl \
		libs/glm/mat4x2.hpp \
		libs/glm/detail/type_mat4x2.hpp \
		libs/glm/detail/type_mat4x2.inl \
		libs/glm/mat4x3.hpp \
		libs/glm/detail/type_mat4x3.hpp \
		libs/glm/detail/type_mat4x3.inl \
		libs/glm/mat4x4.hpp \
		libs/glm/detail/type_mat4x4.hpp \
		libs/glm/detail/type_mat4x4.inl \
		libs/glm/trigonometric.hpp \
		libs/glm/detail/func_trigonometric.hpp \
		libs/glm/detail/func_trigonometric.inl \
		libs/glm/detail/_vectorize.hpp \
		libs/glm/detail/type_vec1.hpp \
		libs/glm/detail/type_vec1.inl \
		libs/glm/exponential.hpp \
		libs/glm/detail/func_exponential.hpp \
		libs/glm/detail/func_exponential.inl \
		libs/glm/detail/func_vector_relational.hpp \
		libs/glm/detail/func_vector_relational.inl \
		libs/glm/common.hpp \
		libs/glm/detail/func_common.hpp \
		libs/glm/detail/func_common.inl \
		libs/glm/packing.hpp \
		libs/glm/detail/func_packing.hpp \
		libs/glm/detail/func_packing.inl \
		libs/glm/detail/type_half.hpp \
		libs/glm/detail/type_half.inl \
		libs/glm/geometric.hpp \
		libs/glm/detail/func_geometric.hpp \
		libs/glm/detail/func_geometric.inl \
		libs/glm/matrix.hpp \
		libs/glm/detail/func_matrix.hpp \
		libs/glm/detail/func_matrix.inl \
		libs/glm/vector_relational.hpp \
		libs/glm/integer.hpp \
		libs/glm/detail/func_integer.hpp \
		libs/glm/detail/func_integer.inl \
		libs/glm/gtc/type_ptr.hpp \
		libs/glm/gtc/quaternion.hpp \
		libs/glm/gtc/constants.hpp \
		libs/glm/gtc/constants.inl \
		libs/glm/gtx/quaternion.inl \
		libs/glm/gtc/type_ptr.inl \
		src/engine/graphics/GraphicsDebug.h \
		src/engine/graphics/Texture2D.h \
		src/engine/graphics/Texture.h \
		src/engine/util/CommonIncludes.h \
		libs/glm/gtx/string_cast.hpp \
		libs/glm/gtx/integer.hpp \
		libs/glm/gtx/integer.inl \
		libs/glm/gtx/quaternion.hpp \
		libs/glm/gtx/norm.hpp \
		libs/glm/gtx/norm.inl \
		libs/glm/gtx/string_cast.inl \
		libs/glm/gtx/transform.hpp \
		libs/glm/gtc/matrix_transform.hpp \
		libs/glm/gtc/matrix_transform.inl \
		libs/glm/gtx/transform.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Shader.o src/engine/graphics/Shader.cpp

Camera.o: src/engine/graphics/Camera.cpp src/engine/graphics/Camera.h \
		src/engine/util/CommonIncludes.h \
		libs/glew-1.10.0/include/GL/glew.h \
		libs/glm/glm.hpp \
		libs/glm/detail/_fixes.hpp \
		libs/glm/fwd.hpp \
		libs/glm/detail/type_int.hpp \
		libs/glm/detail/setup.hpp \
		libs/glm/detail/type_float.hpp \
		libs/glm/detail/type_vec.hpp \
		libs/glm/detail/precision.hpp \
		libs/glm/detail/type_mat.hpp \
		libs/glm/vec2.hpp \
		libs/glm/detail/type_vec2.hpp \
		libs/glm/detail/_swizzle.hpp \
		libs/glm/detail/_swizzle_func.hpp \
		libs/glm/detail/type_vec2.inl \
		libs/glm/vec3.hpp \
		libs/glm/detail/type_vec3.hpp \
		libs/glm/detail/type_vec3.inl \
		libs/glm/vec4.hpp \
		libs/glm/detail/type_vec4.hpp \
		libs/glm/detail/type_vec4.inl \
		libs/glm/mat2x2.hpp \
		libs/glm/detail/type_mat2x2.hpp \
		libs/glm/detail/type_mat2x2.inl \
		libs/glm/mat2x3.hpp \
		libs/glm/detail/type_mat2x3.hpp \
		libs/glm/detail/type_mat2x3.inl \
		libs/glm/mat2x4.hpp \
		libs/glm/detail/type_mat2x4.hpp \
		libs/glm/detail/type_mat2x4.inl \
		libs/glm/mat3x2.hpp \
		libs/glm/detail/type_mat3x2.hpp \
		libs/glm/detail/type_mat3x2.inl \
		libs/glm/mat3x3.hpp \
		libs/glm/detail/type_mat3x3.hpp \
		libs/glm/detail/type_mat3x3.inl \
		libs/glm/mat3x4.hpp \
		libs/glm/detail/type_mat3x4.hpp \
		libs/glm/detail/type_mat3x4.inl \
		libs/glm/mat4x2.hpp \
		libs/glm/detail/type_mat4x2.hpp \
		libs/glm/detail/type_mat4x2.inl \
		libs/glm/mat4x3.hpp \
		libs/glm/detail/type_mat4x3.hpp \
		libs/glm/detail/type_mat4x3.inl \
		libs/glm/mat4x4.hpp \
		libs/glm/detail/type_mat4x4.hpp \
		libs/glm/detail/type_mat4x4.inl \
		libs/glm/trigonometric.hpp \
		libs/glm/detail/func_trigonometric.hpp \
		libs/glm/detail/func_trigonometric.inl \
		libs/glm/detail/_vectorize.hpp \
		libs/glm/detail/type_vec1.hpp \
		libs/glm/detail/type_vec1.inl \
		libs/glm/exponential.hpp \
		libs/glm/detail/func_exponential.hpp \
		libs/glm/detail/func_exponential.inl \
		libs/glm/detail/func_vector_relational.hpp \
		libs/glm/detail/func_vector_relational.inl \
		libs/glm/common.hpp \
		libs/glm/detail/func_common.hpp \
		libs/glm/detail/func_common.inl \
		libs/glm/packing.hpp \
		libs/glm/detail/func_packing.hpp \
		libs/glm/detail/func_packing.inl \
		libs/glm/detail/type_half.hpp \
		libs/glm/detail/type_half.inl \
		libs/glm/geometric.hpp \
		libs/glm/detail/func_geometric.hpp \
		libs/glm/detail/func_geometric.inl \
		libs/glm/matrix.hpp \
		libs/glm/detail/func_matrix.hpp \
		libs/glm/detail/func_matrix.inl \
		libs/glm/vector_relational.hpp \
		libs/glm/integer.hpp \
		libs/glm/detail/func_integer.hpp \
		libs/glm/detail/func_integer.inl \
		libs/glm/gtx/string_cast.hpp \
		libs/glm/gtx/integer.hpp \
		libs/glm/gtx/integer.inl \
		libs/glm/gtx/quaternion.hpp \
		libs/glm/gtc/constants.hpp \
		libs/glm/gtc/constants.inl \
		libs/glm/gtc/quaternion.hpp \
		libs/glm/gtx/quaternion.inl \
		libs/glm/gtx/norm.hpp \
		libs/glm/gtx/norm.inl \
		libs/glm/gtx/string_cast.inl \
		libs/glm/gtx/transform.hpp \
		libs/glm/gtc/matrix_transform.hpp \
		libs/glm/gtc/matrix_transform.inl \
		libs/glm/gtx/transform.inl \
		libs/glm/gtc/type_ptr.hpp \
		libs/glm/gtc/type_ptr.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Camera.o src/engine/graphics/Camera.cpp

Shape.o: src/engine/graphics/Shape.cpp src/engine/graphics/Shape.h \
		src/engine/util/CommonIncludes.h \
		libs/glew-1.10.0/include/GL/glew.h \
		libs/glm/glm.hpp \
		libs/glm/detail/_fixes.hpp \
		libs/glm/fwd.hpp \
		libs/glm/detail/type_int.hpp \
		libs/glm/detail/setup.hpp \
		libs/glm/detail/type_float.hpp \
		libs/glm/detail/type_vec.hpp \
		libs/glm/detail/precision.hpp \
		libs/glm/detail/type_mat.hpp \
		libs/glm/vec2.hpp \
		libs/glm/detail/type_vec2.hpp \
		libs/glm/detail/_swizzle.hpp \
		libs/glm/detail/_swizzle_func.hpp \
		libs/glm/detail/type_vec2.inl \
		libs/glm/vec3.hpp \
		libs/glm/detail/type_vec3.hpp \
		libs/glm/detail/type_vec3.inl \
		libs/glm/vec4.hpp \
		libs/glm/detail/type_vec4.hpp \
		libs/glm/detail/type_vec4.inl \
		libs/glm/mat2x2.hpp \
		libs/glm/detail/type_mat2x2.hpp \
		libs/glm/detail/type_mat2x2.inl \
		libs/glm/mat2x3.hpp \
		libs/glm/detail/type_mat2x3.hpp \
		libs/glm/detail/type_mat2x3.inl \
		libs/glm/mat2x4.hpp \
		libs/glm/detail/type_mat2x4.hpp \
		libs/glm/detail/type_mat2x4.inl \
		libs/glm/mat3x2.hpp \
		libs/glm/detail/type_mat3x2.hpp \
		libs/glm/detail/type_mat3x2.inl \
		libs/glm/mat3x3.hpp \
		libs/glm/detail/type_mat3x3.hpp \
		libs/glm/detail/type_mat3x3.inl \
		libs/glm/mat3x4.hpp \
		libs/glm/detail/type_mat3x4.hpp \
		libs/glm/detail/type_mat3x4.inl \
		libs/glm/mat4x2.hpp \
		libs/glm/detail/type_mat4x2.hpp \
		libs/glm/detail/type_mat4x2.inl \
		libs/glm/mat4x3.hpp \
		libs/glm/detail/type_mat4x3.hpp \
		libs/glm/detail/type_mat4x3.inl \
		libs/glm/mat4x4.hpp \
		libs/glm/detail/type_mat4x4.hpp \
		libs/glm/detail/type_mat4x4.inl \
		libs/glm/trigonometric.hpp \
		libs/glm/detail/func_trigonometric.hpp \
		libs/glm/detail/func_trigonometric.inl \
		libs/glm/detail/_vectorize.hpp \
		libs/glm/detail/type_vec1.hpp \
		libs/glm/detail/type_vec1.inl \
		libs/glm/exponential.hpp \
		libs/glm/detail/func_exponential.hpp \
		libs/glm/detail/func_exponential.inl \
		libs/glm/detail/func_vector_relational.hpp \
		libs/glm/detail/func_vector_relational.inl \
		libs/glm/common.hpp \
		libs/glm/detail/func_common.hpp \
		libs/glm/detail/func_common.inl \
		libs/glm/packing.hpp \
		libs/glm/detail/func_packing.hpp \
		libs/glm/detail/func_packing.inl \
		libs/glm/detail/type_half.hpp \
		libs/glm/detail/type_half.inl \
		libs/glm/geometric.hpp \
		libs/glm/detail/func_geometric.hpp \
		libs/glm/detail/func_geometric.inl \
		libs/glm/matrix.hpp \
		libs/glm/detail/func_matrix.hpp \
		libs/glm/detail/func_matrix.inl \
		libs/glm/vector_relational.hpp \
		libs/glm/integer.hpp \
		libs/glm/detail/func_integer.hpp \
		libs/glm/detail/func_integer.inl \
		libs/glm/gtx/string_cast.hpp \
		libs/glm/gtx/integer.hpp \
		libs/glm/gtx/integer.inl \
		libs/glm/gtx/quaternion.hpp \
		libs/glm/gtc/constants.hpp \
		libs/glm/gtc/constants.inl \
		libs/glm/gtc/quaternion.hpp \
		libs/glm/gtx/quaternion.inl \
		libs/glm/gtx/norm.hpp \
		libs/glm/gtx/norm.inl \
		libs/glm/gtx/string_cast.inl \
		libs/glm/gtx/transform.hpp \
		libs/glm/gtc/matrix_transform.hpp \
		libs/glm/gtc/matrix_transform.inl \
		libs/glm/gtx/transform.inl \
		libs/glm/gtc/type_ptr.hpp \
		libs/glm/gtc/type_ptr.inl \
		src/engine/graphics/VBO.h \
		src/engine/graphics/IBO.h \
		src/engine/graphics/VBOAttribMarker.h \
		src/engine/graphics/ShaderAttribLocations.h \
		src/engine/graphics/Graphics.h \
		src/engine/graphics/Shader.h \
		src/engine/graphics/GraphicsDebug.h \
		src/engine/graphics/Constants.h \
		src/engine/graphics/Material.h \
		src/engine/graphics/Light.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Shape.o src/engine/graphics/Shape.cpp

Graphics.o: src/engine/graphics/Graphics.cpp src/engine/graphics/Graphics.h \
		src/engine/util/CommonIncludes.h \
		libs/glew-1.10.0/include/GL/glew.h \
		libs/glm/glm.hpp \
		libs/glm/detail/_fixes.hpp \
		libs/glm/fwd.hpp \
		libs/glm/detail/type_int.hpp \
		libs/glm/detail/setup.hpp \
		libs/glm/detail/type_float.hpp \
		libs/glm/detail/type_vec.hpp \
		libs/glm/detail/precision.hpp \
		libs/glm/detail/type_mat.hpp \
		libs/glm/vec2.hpp \
		libs/glm/detail/type_vec2.hpp \
		libs/glm/detail/_swizzle.hpp \
		libs/glm/detail/_swizzle_func.hpp \
		libs/glm/detail/type_vec2.inl \
		libs/glm/vec3.hpp \
		libs/glm/detail/type_vec3.hpp \
		libs/glm/detail/type_vec3.inl \
		libs/glm/vec4.hpp \
		libs/glm/detail/type_vec4.hpp \
		libs/glm/detail/type_vec4.inl \
		libs/glm/mat2x2.hpp \
		libs/glm/detail/type_mat2x2.hpp \
		libs/glm/detail/type_mat2x2.inl \
		libs/glm/mat2x3.hpp \
		libs/glm/detail/type_mat2x3.hpp \
		libs/glm/detail/type_mat2x3.inl \
		libs/glm/mat2x4.hpp \
		libs/glm/detail/type_mat2x4.hpp \
		libs/glm/detail/type_mat2x4.inl \
		libs/glm/mat3x2.hpp \
		libs/glm/detail/type_mat3x2.hpp \
		libs/glm/detail/type_mat3x2.inl \
		libs/glm/mat3x3.hpp \
		libs/glm/detail/type_mat3x3.hpp \
		libs/glm/detail/type_mat3x3.inl \
		libs/glm/mat3x4.hpp \
		libs/glm/detail/type_mat3x4.hpp \
		libs/glm/detail/type_mat3x4.inl \
		libs/glm/mat4x2.hpp \
		libs/glm/detail/type_mat4x2.hpp \
		libs/glm/detail/type_mat4x2.inl \
		libs/glm/mat4x3.hpp \
		libs/glm/detail/type_mat4x3.hpp \
		libs/glm/detail/type_mat4x3.inl \
		libs/glm/mat4x4.hpp \
		libs/glm/detail/type_mat4x4.hpp \
		libs/glm/detail/type_mat4x4.inl \
		libs/glm/trigonometric.hpp \
		libs/glm/detail/func_trigonometric.hpp \
		libs/glm/detail/func_trigonometric.inl \
		libs/glm/detail/_vectorize.hpp \
		libs/glm/detail/type_vec1.hpp \
		libs/glm/detail/type_vec1.inl \
		libs/glm/exponential.hpp \
		libs/glm/detail/func_exponential.hpp \
		libs/glm/detail/func_exponential.inl \
		libs/glm/detail/func_vector_relational.hpp \
		libs/glm/detail/func_vector_relational.inl \
		libs/glm/common.hpp \
		libs/glm/detail/func_common.hpp \
		libs/glm/detail/func_common.inl \
		libs/glm/packing.hpp \
		libs/glm/detail/func_packing.hpp \
		libs/glm/detail/func_packing.inl \
		libs/glm/detail/type_half.hpp \
		libs/glm/detail/type_half.inl \
		libs/glm/geometric.hpp \
		libs/glm/detail/func_geometric.hpp \
		libs/glm/detail/func_geometric.inl \
		libs/glm/matrix.hpp \
		libs/glm/detail/func_matrix.hpp \
		libs/glm/detail/func_matrix.inl \
		libs/glm/vector_relational.hpp \
		libs/glm/integer.hpp \
		libs/glm/detail/func_integer.hpp \
		libs/glm/detail/func_integer.inl \
		libs/glm/gtx/string_cast.hpp \
		libs/glm/gtx/integer.hpp \
		libs/glm/gtx/integer.inl \
		libs/glm/gtx/quaternion.hpp \
		libs/glm/gtc/constants.hpp \
		libs/glm/gtc/constants.inl \
		libs/glm/gtc/quaternion.hpp \
		libs/glm/gtx/quaternion.inl \
		libs/glm/gtx/norm.hpp \
		libs/glm/gtx/norm.inl \
		libs/glm/gtx/string_cast.inl \
		libs/glm/gtx/transform.hpp \
		libs/glm/gtc/matrix_transform.hpp \
		libs/glm/gtc/matrix_transform.inl \
		libs/glm/gtx/transform.inl \
		libs/glm/gtc/type_ptr.hpp \
		libs/glm/gtc/type_ptr.inl \
		src/engine/graphics/Shader.h \
		src/engine/graphics/VBO.h \
		src/engine/graphics/GraphicsDebug.h \
		src/engine/graphics/Constants.h \
		src/engine/graphics/Material.h \
		src/engine/graphics/Light.h \
		src/engine/graphics/ResourceLoader.h \
		src/engine/graphics/CylinderData.h \
		src/engine/graphics/SphereData.h \
		src/engine/graphics/CubeData.h \
		src/engine/graphics/VBOAttribMarker.h \
		src/engine/graphics/ShaderAttribLocations.h \
		src/engine/graphics/Texture.h \
		src/engine/graphics/Texture2D.h \
		src/engine/graphics/Font.h \
		src/engine/graphics/FBO.h \
		src/engine/graphics/Shape.h \
		src/engine/graphics/Camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Graphics.o src/engine/graphics/Graphics.cpp

Material.o: src/engine/graphics/Material.cpp src/engine/graphics/Material.h \
		libs/glm/glm.hpp \
		libs/glm/detail/_fixes.hpp \
		libs/glm/fwd.hpp \
		libs/glm/detail/type_int.hpp \
		libs/glm/detail/setup.hpp \
		libs/glm/detail/type_float.hpp \
		libs/glm/detail/type_vec.hpp \
		libs/glm/detail/precision.hpp \
		libs/glm/detail/type_mat.hpp \
		libs/glm/vec2.hpp \
		libs/glm/detail/type_vec2.hpp \
		libs/glm/detail/_swizzle.hpp \
		libs/glm/detail/_swizzle_func.hpp \
		libs/glm/detail/type_vec2.inl \
		libs/glm/vec3.hpp \
		libs/glm/detail/type_vec3.hpp \
		libs/glm/detail/type_vec3.inl \
		libs/glm/vec4.hpp \
		libs/glm/detail/type_vec4.hpp \
		libs/glm/detail/type_vec4.inl \
		libs/glm/mat2x2.hpp \
		libs/glm/detail/type_mat2x2.hpp \
		libs/glm/detail/type_mat2x2.inl \
		libs/glm/mat2x3.hpp \
		libs/glm/detail/type_mat2x3.hpp \
		libs/glm/detail/type_mat2x3.inl \
		libs/glm/mat2x4.hpp \
		libs/glm/detail/type_mat2x4.hpp \
		libs/glm/detail/type_mat2x4.inl \
		libs/glm/mat3x2.hpp \
		libs/glm/detail/type_mat3x2.hpp \
		libs/glm/detail/type_mat3x2.inl \
		libs/glm/mat3x3.hpp \
		libs/glm/detail/type_mat3x3.hpp \
		libs/glm/detail/type_mat3x3.inl \
		libs/glm/mat3x4.hpp \
		libs/glm/detail/type_mat3x4.hpp \
		libs/glm/detail/type_mat3x4.inl \
		libs/glm/mat4x2.hpp \
		libs/glm/detail/type_mat4x2.hpp \
		libs/glm/detail/type_mat4x2.inl \
		libs/glm/mat4x3.hpp \
		libs/glm/detail/type_mat4x3.hpp \
		libs/glm/detail/type_mat4x3.inl \
		libs/glm/mat4x4.hpp \
		libs/glm/detail/type_mat4x4.hpp \
		libs/glm/detail/type_mat4x4.inl \
		libs/glm/trigonometric.hpp \
		libs/glm/detail/func_trigonometric.hpp \
		libs/glm/detail/func_trigonometric.inl \
		libs/glm/detail/_vectorize.hpp \
		libs/glm/detail/type_vec1.hpp \
		libs/glm/detail/type_vec1.inl \
		libs/glm/exponential.hpp \
		libs/glm/detail/func_exponential.hpp \
		libs/glm/detail/func_exponential.inl \
		libs/glm/detail/func_vector_relational.hpp \
		libs/glm/detail/func_vector_relational.inl \
		libs/glm/common.hpp \
		libs/glm/detail/func_common.hpp \
		libs/glm/detail/func_common.inl \
		libs/glm/packing.hpp \
		libs/glm/detail/func_packing.hpp \
		libs/glm/detail/func_packing.inl \
		libs/glm/detail/type_half.hpp \
		libs/glm/detail/type_half.inl \
		libs/glm/geometric.hpp \
		libs/glm/detail/func_geometric.hpp \
		libs/glm/detail/func_geometric.inl \
		libs/glm/matrix.hpp \
		libs/glm/detail/func_matrix.hpp \
		libs/glm/detail/func_matrix.inl \
		libs/glm/vector_relational.hpp \
		libs/glm/integer.hpp \
		libs/glm/detail/func_integer.hpp \
		libs/glm/detail/func_integer.inl \
		src/engine/graphics/Texture2D.h \
		src/engine/graphics/Texture.h \
		src/engine/util/CommonIncludes.h \
		libs/glew-1.10.0/include/GL/glew.h \
		libs/glm/gtx/string_cast.hpp \
		libs/glm/gtx/integer.hpp \
		libs/glm/gtx/integer.inl \
		libs/glm/gtx/quaternion.hpp \
		libs/glm/gtc/constants.hpp \
		libs/glm/gtc/constants.inl \
		libs/glm/gtc/quaternion.hpp \
		libs/glm/gtx/quaternion.inl \
		libs/glm/gtx/norm.hpp \
		libs/glm/gtx/norm.inl \
		libs/glm/gtx/string_cast.inl \
		libs/glm/gtx/transform.hpp \
		libs/glm/gtc/matrix_transform.hpp \
		libs/glm/gtc/matrix_transform.inl \
		libs/glm/gtx/transform.inl \
		libs/glm/gtc/type_ptr.hpp \
		libs/glm/gtc/type_ptr.inl \
		src/engine/graphics/Shader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Material.o src/engine/graphics/Material.cpp

Light.o: src/engine/graphics/Light.cpp src/engine/graphics/Light.h \
		libs/glm/glm.hpp \
		libs/glm/detail/_fixes.hpp \
		libs/glm/fwd.hpp \
		libs/glm/detail/type_int.hpp \
		libs/glm/detail/setup.hpp \
		libs/glm/detail/type_float.hpp \
		libs/glm/detail/type_vec.hpp \
		libs/glm/detail/precision.hpp \
		libs/glm/detail/type_mat.hpp \
		libs/glm/vec2.hpp \
		libs/glm/detail/type_vec2.hpp \
		libs/glm/detail/_swizzle.hpp \
		libs/glm/detail/_swizzle_func.hpp \
		libs/glm/detail/type_vec2.inl \
		libs/glm/vec3.hpp \
		libs/glm/detail/type_vec3.hpp \
		libs/glm/detail/type_vec3.inl \
		libs/glm/vec4.hpp \
		libs/glm/detail/type_vec4.hpp \
		libs/glm/detail/type_vec4.inl \
		libs/glm/mat2x2.hpp \
		libs/glm/detail/type_mat2x2.hpp \
		libs/glm/detail/type_mat2x2.inl \
		libs/glm/mat2x3.hpp \
		libs/glm/detail/type_mat2x3.hpp \
		libs/glm/detail/type_mat2x3.inl \
		libs/glm/mat2x4.hpp \
		libs/glm/detail/type_mat2x4.hpp \
		libs/glm/detail/type_mat2x4.inl \
		libs/glm/mat3x2.hpp \
		libs/glm/detail/type_mat3x2.hpp \
		libs/glm/detail/type_mat3x2.inl \
		libs/glm/mat3x3.hpp \
		libs/glm/detail/type_mat3x3.hpp \
		libs/glm/detail/type_mat3x3.inl \
		libs/glm/mat3x4.hpp \
		libs/glm/detail/type_mat3x4.hpp \
		libs/glm/detail/type_mat3x4.inl \
		libs/glm/mat4x2.hpp \
		libs/glm/detail/type_mat4x2.hpp \
		libs/glm/detail/type_mat4x2.inl \
		libs/glm/mat4x3.hpp \
		libs/glm/detail/type_mat4x3.hpp \
		libs/glm/detail/type_mat4x3.inl \
		libs/glm/mat4x4.hpp \
		libs/glm/detail/type_mat4x4.hpp \
		libs/glm/detail/type_mat4x4.inl \
		libs/glm/trigonometric.hpp \
		libs/glm/detail/func_trigonometric.hpp \
		libs/glm/detail/func_trigonometric.inl \
		libs/glm/detail/_vectorize.hpp \
		libs/glm/detail/type_vec1.hpp \
		libs/glm/detail/type_vec1.inl \
		libs/glm/exponential.hpp \
		libs/glm/detail/func_exponential.hpp \
		libs/glm/detail/func_exponential.inl \
		libs/glm/detail/func_vector_relational.hpp \
		libs/glm/detail/func_vector_relational.inl \
		libs/glm/common.hpp \
		libs/glm/detail/func_common.hpp \
		libs/glm/detail/func_common.inl \
		libs/glm/packing.hpp \
		libs/glm/detail/func_packing.hpp \
		libs/glm/detail/func_packing.inl \
		libs/glm/detail/type_half.hpp \
		libs/glm/detail/type_half.inl \
		libs/glm/geometric.hpp \
		libs/glm/detail/func_geometric.hpp \
		libs/glm/detail/func_geometric.inl \
		libs/glm/matrix.hpp \
		libs/glm/detail/func_matrix.hpp \
		libs/glm/detail/func_matrix.inl \
		libs/glm/vector_relational.hpp \
		libs/glm/integer.hpp \
		libs/glm/detail/func_integer.hpp \
		libs/glm/detail/func_integer.inl \
		src/engine/graphics/Constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Light.o src/engine/graphics/Light.cpp

qrc_shaders.o: qrc_shaders.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_shaders.o qrc_shaders.cpp

qrc_fonts.o: qrc_fonts.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_fonts.o qrc_fonts.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_view.o: moc_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_view.o moc_view.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

